# Generated by Django 3.2.5 on 2021-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_rtc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login',
            field=models.CharField(max_length=50),
        ),
    ]
