# Generated by Django 3.2.5 on 2021-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_rtc', '0002_alter_profile_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
